version: '2'
services:
  be:
    build: .
    environment:
      - NODE_ENV=production
    restart: always
  nginx:
    image: nginx:latest
    depends_on:
      - be
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/logs:/var/logs
    ports:
      - "3000:80"
    restart: always
    